### ISSUE TITLE
Be able to disable logs

### ISSUE THREAD

**Issue by Dathin** [Unleash/unleash-client-python#165]
**Is your feature request related to a problem? Please describe.**
I'm having some trouble at unleash logs. The major part of my logs are unleash related logs for now, most of the logs are related to job runs at appscheduler, fetch_and_load_features and aggregate_and_send_metrics.
While using cloud functions the price increased considerably. 

**Describe the solution you'd like**
I would like to be able to disable logs comming from unleash-client-python easily. Or at least the ones comming from appscheduler. I imagine somethign like this: 
```python
UnleashClient(
    url="myurl.com",
    app_name="myAppName",
    disable_logs=False,
    disable_job_logs=True
)
```

**Describe alternatives you've considered**
If this is not possible to implement I would love to hear by you what should be the best way to fork it and build on my own.

**Additional context**
My logs example: 
![image](https://user-images.githubusercontent.com/34101091/124168339-611c2880-da7b-11eb-83b6-7f1a5cb468fe.png)

**Comment by wbolster** [comment]
something like this may help you:

```
import logging

logging.getLogger("UnleashClient").setLevel(logging.ERROR)
```

**Comment by ivanklee86** [comment]
Hi Danthin!  I think you're seeing those log statements because your application's logging at the debug level.  There's an example [here](https://github.com/Unleash/unleash-client-python/blob/master/tests/integration_tests/integration_unleashhosted.py#L34) that you can tweak to play with log levels on a whole.

There's also a few options from this thread on [StackOverflow](https://stackoverflow.com/questions/16763749/python-apscheduler-how-to-disable-logging) to just tweak the logger for APScheduler too, though I haven't personally used it.

**Comment by Dathin** [comment]
That helped a lot. And explained I was not able to see this logs locally.

Closing it now. Thank you a lot guys =)
