### ISSUE TITLE
Returning "name": "disabled" when getting variants using Python SDK

### ISSUE THREAD

**Issue by renzpaoloabergos** [Unleash/unleash-client-python#197]
**Describe the bug**
When using the unleash client's `get_variant` function, we are receiving unexpected results:
```
context = {"userId": "YdTFXyyh463XQbZK"}
variant = unleash_client.get_variant("live.gbdt_v5_20220309_active_user", context)

Result:
{'name': 'disabled', 'enabled': True}
```

**To Reproduce**
1. Create feature toggle with the name `live.gbdt_v5_20220309_active_user`
2. Populate at least 1 random variant
3. Try getting a variant with that user id and feature toggle name

**Expected behavior**
We expect it to return a randomized variant with its payload.

**Logs**
```
{'userId': 'YdTFXyyh463XQbZK'}
FEATURE TOGGLE: live.gbdt_v5_20220309_active_user
ENABLED:  True
VARIANT:  {'name': 'disabled', 'enabled': True}
```

**Additional context**

**Comment by ivanklee86** [comment]
Hello!

ucp _generally_ returns a `disabled` when the feature flag isn't enabled (or there's some other weird provisioning) or there's no variants.  

I set up this [test feature flag](https://app.unleash-hosted.com/demo/projects/default/features/live.gbdt_v5_20220309_active_user) and was able to get the expected behavior.

However, there's the possibility it might set the `enabled` flag if there was an exception during evaluation: [here](https://github.com/Unleash/unleash-client-python/blob/13687698f0aec15f61bfa14a0d1cca248c836ed0/UnleashClient/features/Feature.py#L97)

However!  I did find that I had somehow accidently disabled logging for unleashclient.  o.O I'm going to release a new version this AM with a fix.  Would you mind retesting after it's released?

**Comment by ivanklee86** [comment]
Could you pleas try again with v5.1.1?

**Comment by renzpaoloabergos** [comment]
Hi @ivanklee86 tried it and can see logs in our instance, example:
```
Unable to get feature flag toggles, using cached provisioning.

```

However, the `{'name': 'disabled', 'enabled': True}` is still weird. Feature toggle is enabled (also checked if initialized, even lowered the refresh interval) but still uses the disabled variation..

**Comment by renzpaoloabergos** [comment]
Thanks for reaching out and trying to explain how it occurs! 💯

**Comment by ivarconr** [comment]
Is this still an issue?
