### ISSUE TITLE
If initialization fails, client still returns True for is_initialized

### ISSUE THREAD

**Issue by Kip620** [Unleash/unleash-client-python#233]
**Describe the bug**
During `initialize_client()`, if the UnleashClient is given the wrong url or instance_id we will raise an exception during the get_feature_toggles() and then continue. Since the exception is raised inside `fetch_and_load_features` and `fetch_toggles` we will never hit the exception in the outer method which will result in `is_initialized` getting set to TRUE

**To Reproduce**
1. Set up a new UnleashClient with a false url. 
2. Initialize the client and then return `client.is_initialized` to see if its set to True

Sample code is welcome!

**Expected behavior**
After failing to initialize, we want to set the `is_initialized()` to False
I'm not sure the right path to solve, either setting the `self.is_initialized` inside the smaller `get_feature_toggles()` (probably not a great option) or bubbling up the exception when `fetch_toggles` is run so that the exception in the outer method is caught.

**Logs**
If applicable, add logs or output to help explain your problem.
Error Trace:
UnleashClient - WARNING - Unleash Client feature fetch failed due to unexpected HTTP status code.
UnleashClient - ERROR - Unleash Client feature fetch failed due to exception: Unleash Client feature fetch failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/UnleashClient/api/features.py", line 64, in get_feature_toggles
    raise Exception("Unleash Client feature fetch failed!")
Exception: Unleash Client feature fetch failed!

-> client.is_initialized = True

**Additional context**
We'd like to set a different flow of logic based on if the client is or isn't initialized. Right now the `fallback_function` can work as a workaround. But using a default flag might not always be the right course of action for when the client isn't initialized.

**Comment by andreas-unleash** [comment]
Hi @Kip620! Thanks for bringing this to our attention. I will bring it up with the team and get back to you.

**Comment by sighphyre** [comment]
Hey @Kip620, this is actually the way the SDK is designed (not saying it's not a bug but this was intentional). The idea here is that when you initialise the client, the server may or may not be accessible right now, but it's expected to be accessible in the near future. If the client can't hit the Unleash server, it should load the backup file, meaning it will be initialised with the last known fetch from the last time it was run.  That's probably not something I want to change directly, but I would be open to adding a `fail_fast` or equivalent parameter to the initialise so that you can opt into this behaviour if needed.

I am interested though, what is the different logic flow you're trying to implement if the SDK can't sync on startup?
