### ISSUE TITLE
ETag test failing

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash-client-python#275]
**Describe the bug**
ETag test in `tests/unit_tests/api/test_feature.py:92` is broken.

**To Reproduce**
1. Run tests

**Additional context**
It's skipping this test was pushed forward in time multiple times. Let's track this issue and attempts to solve it here.

**Comment by yjabri** [comment]
I believe the problem is the argument `json={}` in the [`responses.add(...)`](https://github.com/Unleash/unleash-client-python/blob/main/tests/unit_tests/api/test_feature.py#L81.). According to [RFC 7232 - 4.1 304 Not Modified](https://datatracker.ietf.org/doc/html/rfc7232#section-4.1)
>A 304 response cannot contain a message-body; it is always terminated by the first empty line after the header field

I think that's why calling `session.get` in the test raises
```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(2 bytes read, -2 more expected)', IncompleteRead(2 bytes read, -2 more expected))
```

I validated that removing the argument and changing the mock to
```
responses.add(
    responses.GET, PROJECT_URL, status=304, headers={"etag": ETAG_VALUE}
)
```
makes the test pass.

**Comment by Tymek** [comment]
@yjabri If you confirmed that it will make tests pass, PRs are welcome 👍🏻
You can try tests in CI with a PR Draft

**Comment by yjabri** [comment]
@Tymek Does this PR look okay to you? I believe it addresses the problem raised.
