### ISSUE TITLE
Why does the test cases in unit_tests/test_client.py requires sleep before assertion?

### ISSUE THREAD

**Issue by raheemazeezabiodun** [Unleash/unleash-client-python#287]
We currently use Unleash in my workplace and intend not to mock the library in the integration test as we can use the admin API to set up our features and use the library as it is since we host it

However, I'm experiencing flaky behavior sometimes asserting whether a feature is enabled. I noticed that whenever the client is initialized in the test, we sleep the thread for a second, example [here](https://github.com/Unleash/unleash-client-python/blob/main/tests/unit_tests/test_client.py#L276)

Is this because the library uses AppScheduler under the hood and I also have to sleep after initializing the client?

Example here:

```
client = UnleashClient(...).initalize_client()

assert client.is_enabled("flag")
```

Whenever this fails, it always prints this out.
```
INFO  [apscheduler.scheduler] Scheduler started
INFO  [apscheduler.scheduler] Added job "fetch_and_load_features" to job store "default"
INFO  [apscheduler.scheduler] Added job "aggregate_and_send_metrics" to job store "default"
-------------------------------------------------- Captured log call ---------------------------------------------------
INFO     apscheduler.scheduler:base.py:171 Scheduler started
INFO     apscheduler.scheduler:base.py:885 Added job "fetch_and_load_features" to job store "default"
INFO     apscheduler.scheduler:base.py:885 Added job "aggregate_and_send_metrics" to job store "default"

```

However, if I update the test by sleeping for a second, the result is deterministic
```
client = UnleashClient(...).initalize_client()
time.sleep(1)
assert client.is_enabled("flag")
```

**Comment by raheemazeezabiodun** [comment]
It's worth noting that we set the `refresh_interval` to `30`

```python
UnleashClient(
    refresh_interval=30,
    ....
)
```

**Comment by nunogois** [comment]
Hi @raheemazeezabiodun, thanks for raising this issue. I believe you are correct, but @sighphyre may be able to give you a better answer.

What I can suggest is, depending if it's viable in your use case and tests, that you try using a bootstrap approach instead of mocking. Here's an example of what I mean: https://github.com/Unleash/unleash-client-python/pull/285#discussion_r1384580640

**Comment by sighphyre** [comment]
Hey @raheemazeezabiodun, I think @nunogois suggestion of using the bootstrap is a great suggestion for tests!

But I'd also like to dig a little here because I don't think this should be happening. The sleep(s) that you mention probably should have been taken out a long time ago. Some of those are necessary in the test suite to force the metrics poll to trigger but most are there from when this client wouldn't immediately force a sync to the server. Removing that sleep and running that test in a tight loop always succeeds for me.

I can't see an obvious issue here, a simple test script like this:

```
from UnleashClient import UnleashClient

client = UnleashClient(
    url="https://sandbox.getunleash.io/demo2/api/",
    app_name="test-dev22",
    cache_directory="/tmp/python-sdk-cache",
    custom_headers={
        "Authorization": "*:development.77c610a6b830be12395b9c96043c520a663da808d7655ea437f6b8d1"
    },
)

print("Pre init", client.is_initialized)
client.initialize_client()
print("Post init", client.is_initialized)

print(client.is_enabled("toggle"))
```
Always returns true for me on the latest version of the SDK, regardless of having a backup present or not.

Could you share the remainder of your client setup:

```
UnleashClient(
    refresh_interval=30,
    .... //whatever other properties you have here may be useful
)
```

Is this a web application using something like Django? Just want to isolate a case where you have multiple processes in the mix ontop of the APScheduler's thread pool

**Comment by raheemazeezabiodun** [comment]
@sighphyre , It's a web application using flask.  I'll try the bootstrap method and let you know how that works.


In the meantime, we set up the unleash feature with the strategy via admin apis but here are some details

```
# docker image
image: unleashorg/unleash-server:5

# python library
unleashclient: 5.8.0
```

```python
from UnleashClient import UnleashClient

client = UnleashClient(
       url="http://unleash-server:4242/api",    # this port is binded to the port exposed in the docker container
       app_name="lorep",
       custom_headers={'Authorization': UNLEASH_API_KEY},
       refresh_interval=30,  # todo: evaluate this
       disable_metrics=False,
  )
)
```

**Comment by sighphyre** [comment]
Thanks for the info @raheemazeezabiodun!

Would you mind trying my tiny script and seeing you can reproduce the problem?

Flask may be the cause of this. Or more correctly whatever you're using to run your flask app. Usually I see folks running Flask with uWSGI or something similar, which does spawn off processes behind the scenes and can interfere with the polling thread. I don't believe it's that because thread sleep usually does not sort out that problem, but it might be worth checking this: https://docs.getunleash.io/unleash-client-python/wsgi.html

**Comment by raheemazeezabiodun** [comment]
@sighphyre , I ended up using the bootstrap method and it worked pretty well and was very consistent. T
